---
# tasks file for nginx_php-fpm
- name: install packages
  apt:
    name:
      - nginx
      - php{{ php_version }}-fpm
    state: latest
    cache_valid_time: 3600    # update cache if more than an hour old

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: start php-fpm
  service:
    name: php{{ php_version }}-fpm.service
    state: started
    enabled: yes

- name: create www.conf from template
  template:
    src: ../templates/www.conf.j2
    dest: /etc/php/8.0/fpm/pool.d/www.conf
    backup: true
  notify: restart php-fpm

- name: delete nginx default site
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-available/default
    - /etc/nginx/sites-enabled/default

- name: create nginx root dir
  file:
    path: "{{ nginx_root_dir }}"
    state: directory

- name: create index.php
  copy:
    content: "<?php phpinfo();?>"
    dest: "{{ nginx_root_dir }}/index.php"

- name: create nginx site from template
  template:
    src: ../templates/site.j2
    dest: /etc/nginx/sites-available/{{ nginx_site_name }}
    backup: false

- name: create link in sites-enabled
  file:
    src: /etc/nginx/sites-available/{{ nginx_site_name }}
    dest: /etc/nginx/sites-enabled/{{ nginx_site_name }}
    state: link
  notify: reload nginx
