---
# tasks file for dnsmasq
- name: remove resolv.conf
  file:
    path: /etc/resolv.conf
    state: absent

- name: create resolv.conf from template
  template:
    src: ../templates/resolv.conf.j2
    dest: /etc/resolv.conf
    backup: false

- name: disable systemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: install package
  apt:
    name: dnsmasq
    state: latest
    cache_valid_time: 3600    # update cache if more than an hour old

- name: create dnsmasq.conf from template
  template:
    src: ../templates/dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    backup: true
  notify: restart dnsmasq

- name: start service
  service:
    name: dnsmasq
    state: started
    enabled: yes
